swagger: '2.0'
info:
  description: |
    Base iRODS REST API - including access to primary iRODS user functions like accessing data and metadata,
    setting acls, running queries
  version: 1.0.0
  title: iRODS REST Services Base
  contact:
    name: michael_conway@unc.edu
host: irods.org
basePath: /v1
schemes:
  - https
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
security:
  - basicAuth: []
paths:
  '/collection/{absoluteLogicalPath}/info':
    get:
      tags:
        - files
        - browsing
      summary: List catalog info for the collection
      description: 'List system metadata for the given iRODS collection. This is the catalog metadata for the collection itself, rather than a listing of the children of the collection'
      operationId: collectionInfo
      produces:
        - application/json
        - application/xml
      parameters:
        - name: absoluteLogicalPath
          in: path
          description: Absolute path to the collection in iRODS
          required: true
          type: string
        - name: brief
          in: query
          description: 'Request a full listing of collection information, including gathering metadata and extended attributes, by setting brief to false.'
          required: false
          default: true
          type: boolean
      responses:
          200:
            description: 'A detailed description of the catalog and other metadata about the collection'
            schema:
              $ref: '#/definitions/CollectionInfo'
          404:
            description: Collection information not found
  '/collection/{absoluteLogicalPath}':
    get:
      tags:
        - files
        - browsing
      summary: Do listings of the contents of iRODS collections
      description: 'List children of the given iRODS parent collection.  This is a pagable representation of the direct children of this iRODS parent collection, rather than a recursive listing of the entire subtree'
      operationId: collectionListing
      produces:
        - application/json
        - application/xml
      parameters:
        - name: absoluteLogicalPath
          in: path
          description: Absolute path to the collection in iRODS
          required: true
          type: string
      responses:
        '404':
          description: Collection not found
definitions:
  CollectionInfo:
    type: object
    properties:
      file:
        type: boolean
        format: boolean
        description: true if this is a file
      id:
        type: integer
        description: unique id of the collection
      absolutePath:
        type: string
        description: absoluteIrodsPath
      lastPathComponent:
        type: string
        description: 'the last part of the collection path, which is the display name of the actual collection being viewed'
      collectionParentAbsolutePath:
        type: string
        description: 'fully qualified absolute path, with no trailing slash, of the parent of the given collection'
      pathComponents:
        type: array
        description: array of path components without slashes
        items:
          $ref: "#/definitions/PathComponent"
      collectionOwnerName:
        type: string
        description: 'iRODS user name of the owner of the collection'
      collectionOwnerZone:
        type: string
        description: 'iRODS zone of the owner of the collection'
      inheritance:
        type: boolean
        description: 'indicates whether permissions are inherited by child objects'
      createdDate:
        type: string
        format: dateTime
        description: 'date-time when collection was created'
      modifiedDate:
        type: string
        format: dateTime
        description: 'date-time when collection was last modified'
      starred:
        type: boolean
        description: indicates if the collection was starred by the user
      shared:
        type: boolean
        description: indicates that the collection has been shared by the user
      tags:
        type: array
        description: User defined tags
        items:
          $ref: "#/definitions/Tag"
      avus:
        type: array
        description: Raw AVU metadata
        items:
          $ref: "#/definitions/Avu"
      acls:
        type: array
        description: User permissions
        items:
          $ref: "#/definitions/Acl"
  Avu:
      type: object
      properties:
        attribute:
          type: string
          description: 'avu attribute part'
        value:
          type: string
          description: 'avu value part'
        unit:
          type: string
          description: 'avu unit part'
  Acl:
    type: object
    properties:
      userName:
        type: string
        description: User name in the given zone that has the permission
      userZone:
        type: string
        description: User zone for this user that has the permission
      userId:
        type: integer
        description: Unique id of the user
      userType:
        type: string
        description: Type of user (rodsadmin | rodsuser)
      permission:
        type: string
        description: Level of permission (OWN | WRITE | READ)
  Tag:
    type: object
    properties:
      userName:
        type: string
        description: User name that created tag (will include user#zone)
      tagData:
        type: string
        description: Actual tag applied by the given user
  PathComponent:
    type: object
    properties:
      parthPart:
        type: string
        description: part of a path

        
      
   
