swagger: '2.0'
info:
  description: |
    A blob of imported code to get us started
  version: 1.0.0
  title: iRODS REST Services Base
  contact:
    name: michael_conway@unc.edu
host: irods.org
basePath: /v1
schemes:
  - https
paths:
  '/collection/{absoluteLogicalPath}/info':
    get:
      tags:
        - files
        - browsing
      summary: List catalog info for the collection
      description: 'List system metadata for the given iRODS collection. This is the catalog metadata for the collection itself, rather than a listing of the children of the collection'
      operationId: collectionInfo
      produces:
        - application/json
        - application/xml
      parameters:
        - name: absoluteLogicalPath
          in: path
          description: Absolute path to the collection in iRODS
          required: true
          type: string
        - name: brief
          in: query
          description: Request a full listing of collection information, including gathering metadata and extended attributes, by setting brief to false.
          required: false
          default: true
          type: boolean
      responses:
        '404':
          description: Collection not found
  '/collection/{absoluteLogicalPath}':
    get:
      tags:
        - files
        - browsing
      summary: Do listings of the contents of iRODS collections
      description: 'List children of the given iRODS parent collection.  This is a pagable representation of the direct children of this iRODS parent collection, rather than a recursive listing of the entire subtree'
      operationId: collectionListing
      produces:
        - application/json
        - application/xml
      parameters:
        - name: absoluteLogicalPath
          in: path
          description: Absolute path to the collection in iRODS
          required: true
          type: string
      responses:
        '404':
          description: Collection not found
definitions:
  AnalysisRequest:
    type: object
    properties:
      appId:
        type: string
        format: string
        description: uuid of the app
      name:
        type: string
        description: display name for the app in notifications and in display
      outputDir:
        type: string
        description: target location for staging of outputs
      createOutputSubdir:
        type: boolean
        description: >-
          indicates whether a separate subdirectory should be created to hold
          the output
      archiveLogs:
        type: boolean
        description: indicates whether log files should be staged back as output
      debug:
        type: boolean
        description: whether to add debug info to the app
      config:
        type: object
        additionalProperties:
          type: string
